# Generated by Django 6.1 on 2026-09-03

from django.db import migrations, models


LEGACY_WEIGHT_KG = {
    "light": 2.0,
    "medium": 10.0,
    "heavy": 50.0,
}


def migrate_parcel_weights(apps, schema_editor):
    Parcel = apps.get_model("app", "Parcel")
    for parcel in Parcel.objects.all().iterator():
        # Prefer an explicitly stored weight from the transitional field.
        weight_kg = float(parcel.weight_kg) if parcel.weight_kg is not None else LEGACY_WEIGHT_KG[parcel.weight_category]
        parcel.weight_kg = weight_kg
        if weight_kg <= 5:
            parcel.vehicle_category = "bike"
        elif weight_kg <= 50:
            parcel.vehicle_category = "car"
        else:
            parcel.vehicle_category = "lorry"
        parcel.save(update_fields=["weight_kg", "vehicle_category"])


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_add_parcel_route_coordinates"),
    ]

    operations = [
        migrations.AddField(
            model_name="parcel",
            name="vehicle_category",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.RunPython(migrate_parcel_weights, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="parcel",
            name="weight_kg",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="parcel",
            name="vehicle_category",
            field=models.CharField(choices=[("bike", "bike"), ("car", "car"), ("lorry", "lorry")], max_length=20),
        ),
        migrations.RemoveField(
            model_name="parcel",
            name="weight_category",
        ),
    ]
